---
- name: Deploy application with Docker
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run hello-world container
      docker_container:
        name: hello-world
        image: hello-world
        state: started
        
