---
- name: Deploy Node.js application with Docker
  hosts: webserver
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove old container if exists
      docker_container:
        name: my-node-app
        state: absent

    - name: Pull latest app image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull
        force_source: true   # ensures latest image is pulled always

    - name: Run Node.js app container
      docker_container:
        name: my-node-app
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:{{ app_port }}"
          
