---
---
- name: Deploy Node.js application with Docker
  hosts: webserver
  become: yes
  vars:
    docker_image: "{{ docker_image | default('gowthamkamparaju/demousr') }}"
    docker_tag: "{{ docker_tag | default('latest') }}"
    app_port: "{{ app_port | default('3000') }}"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run Node.js container
      community.docker.docker_container:
        name: my-node-app
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:3000"
          
