---
- name: Deploy Node.js application with Docker
  hosts: webserver
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest app image from Docker Hub
      docker_image:
        name: gowthamkamparaju/demousr
        tag: 1.0
        source: pull

    - name: Run Node.js app container
      docker_container:
        name: my-node-app
        image: gowthamkamparaju/demousr:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
          
