name: Deploy EC2 on GitHub Commit
 
on:
  push:
    branches:
      - main  # Triggers when commits are pushed to the main branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_IDS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEYS }}
          aws-region: ap-south-1  # Change to your AWS region
 
      - name: Install Terraform
        run: |
          sudo apt update && sudo apt install -y wget gpg unzip 
          sudo rm -f /usr/share/keyrings/hashicorp-archive-keyring.gpg
          #wget -o- https://apt.releases.hashicorp.com/gpg |gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          ls -l /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform

      - name: Set Terraform Working Directory
        run: |
         mkdir -p terraform-config
         cd terraform-config
         echo 'terraform { requried_providers { aws = { source = "hashicorp/aws" , version "~> 5.0" } } }' > main.tf
         echo 'provider "aws" {region = "ap-south=1" }' >> main.tf
 
      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-config
 
      - name: Validate Terraform Configuration
        run: terraform validate
 
      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan
        working-directory: terraform-config

 
      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve tfplan
        working-directory: terraform-config
